WIP: Issue/128
E-Edu/task pull request #140
Opened 2020-03-26 15:54 UTC by PAException

## Description

Closes #128 

## Related Issue

## Type of change

- [ ] Bug fix
- [ ] Feature request
- [ ] Documenting code

## Checklists

- [ ] I referenced the according Issue
  - [ ] I created an Issue
  - [ ] I put a link in the Section [Related Issue](#related-issue)
- [ ] I tested my code with multiple browsers
- [ ] My commit messages are good and understandable

2020-03-28 15:56 UTC, steve-hb requested changes

2020-03-28 15:56 UTC, steve-hb commented on .docs/solutionTemplates/controller/solution/SolutionNAMEController.java
> +public class SolutionNAMEController {
CamelCase

2020-03-28 15:56 UTC, steve-hb commented on .docs/solutionTemplates/controller/solution/SolutionNAMEController.java
> +	@Autowired private SolutionNAMERepository solutionNAMERepository;
CamelCase

2020-03-28 15:56 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/controller/solution/WordsaladSolutionController.java
> +		if (this.solutionWordsaladRepository.findById(createWordsaladSolutionDTO.getTaskId()).isPresent()) return ControllerResult.of(Error.ALREADY_EXISTS);
Create method in controller: exists(int taskId)

2020-03-28 15:56 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/controller/solution/WordsaladSolutionController.java
> +		WordsaladSolutionModel wordsaladSolutionModel = new WordsaladSolutionModel();
Use contructor

2020-03-28 15:56 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/controller/solution/WordsaladSolutionController.java
> +		if (this.solutionWordsaladRepository.findById(createWordsaladSolutionDTO.getTaskId()).isPresent()) return ControllerResult.of(Error.ALREADY_EXISTS);
also use repository method for existence

2020-03-28 15:56 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/controller/solution/WordsaladSolutionController.java
> +		if (wordsaladSolutionModel.getSolution().equals(checkWordsaladSolutionDTO.getSolution())) {
equalsIgnoreCase

2020-03-28 15:56 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/controller/solution/WordsaladSolutionController.java
> +		return ControllerResult.of(wordsaladSolutionModel);
where do u update this in the db?

2020-03-28 15:56 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/controller/solution/WordsaladSolutionController.java
> +		if (!this.solutionWordsaladRepository.findById(taskId).isPresent()) return ControllerResult.of(Error.NOT_FOUND);
use exists method

2020-03-28 15:56 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/controller/solution/WordsaladSolutionController.java
> +		if (!solutionWordsaladModels.isPresent()) return ControllerResult.of(Error.NOT_FOUND);
exists method

2020-03-28 15:56 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/controller/solution/WordsaladSolutionController.java
> +		List<Character> characters = new ArrayList<>();
new ArrayList<>(wordsaladSolutionModel.getSolution().length());

2020-03-28 15:56 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/database/repository/solution/SolutionRepository.java
> +
Too many empty lines

2020-03-28 15:56 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/database/repository/solution/SolutionWordsaladRepository.java
> +
Too many empty lines

2020-03-28 15:56 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/endpoint/solution/WordsaladSolutionEndpoint.java
> +	WordsaladSolutionController wordsaladSolutionController;
Same line

2020-03-28 15:56 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/util/ControllerResult.java
> +		if (instance.isErrorPresent()) throw new IllegalArgumentException("No error present in de.themorpheus.edu.taskservice.controller result");
reset

2020-04-02 19:22 UTC, steve-hb requested changes

2020-04-02 19:22 UTC, steve-hb commented on .docs/solutionTemplates/de/themorpheus/edu/taskservice/controller/solution/GenericSolutionController.java
> +	public ControllerResult<GenericSolutionModel> create(CreateGenericSolutionDTO createGenericSolutionDTO) {
create -> createGenericSolutionController
change this everywhere

2020-04-02 19:22 UTC, steve-hb commented on .docs/solutionTemplates/de/themorpheus/edu/taskservice/controller/solution/GenericSolutionController.java
> +		return null;	//TODO: Check if answer is correct
TODO

2020-04-02 19:22 UTC, steve-hb commented on .docs/solutionTemplates/de/themorpheus/edu/taskservice/database/repository/solution/GenericSolutionRepository.java
> +
Only one empty line

2020-04-02 19:22 UTC, steve-hb commented on .docs/solutionTemplates/de/themorpheus/edu/taskservice/endpoint/solution/GenericSolutionEndpoint.java
> +	GenericSolutionController genericSolutionController;
Same fkcing line and private

2020-04-02 19:22 UTC, steve-hb commented on .docs/solutionTemplates/de/themorpheus/edu/taskservice/endpoint/solution/GenericSolutionEndpoint.java
> +	@PostMapping("/solution/Generic")
lowercase

2020-04-02 19:22 UTC, steve-hb commented on .gitignore
> +test.java
dafuq?

2020-04-02 19:22 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/controller/DifficultyController.java
> -
revert

2020-04-02 19:22 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/controller/LectureController.java
> -
revert

2020-04-02 19:22 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/controller/solution/WordsaladSolutionController.java
> +	public ControllerResult<WordsaladSolutionModel> create(CreateWordsaladSolutionDTO dto) {
Im getting headaches

2020-04-02 19:22 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/controller/solution/WordsaladSolutionController.java
> +		for (char c : wordsaladSolutionModel.get().getSolution().toCharArray()) {
remove brackets

2020-04-02 19:22 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/controller/solution/WordsaladSolutionController.java
> +		}
empty line

2020-04-02 19:22 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/endpoint/DifficultyEndpoint.java
> -
revert

2020-04-02 19:22 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/endpoint/LectureEndpoint.java
> -
revert

2020-04-02 19:22 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/endpoint/solution/MultipleChoiceSolutionEndpoint.java
> +	public Object create(@RequestBody @Valid CreateMultipleChoiceSolutionDTO createMultipleChoiceSolutionDTO) {
...

2020-04-02 19:22 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/endpoint/solution/WordsaladSolutionEndpoint.java
> +	public Object create(@RequestBody @Valid CreateWordsaladSolutionDTO createWordsaladSolutionDTO) {
...

2020-04-02 19:22 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/endpoint/solution/WordsaladSolutionEndpoint.java
> +	}
missing empty line

2020-04-02 19:32 UTC, PAException commented on .docs/solutionTemplates/de/themorpheus/edu/taskservice/controller/solution/GenericSolutionController.java
> +		return null;	//TODO: Check if answer is correct
Just the template

2020-04-02 19:42 UTC, PAException commented on src/main/java/de/themorpheus/edu/taskservice/controller/solution/WordsaladSolutionController.java
> +		for (char c : wordsaladSolutionModel.get().getSolution().toCharArray()) {
which one?

2020-04-03 08:25 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/controller/solution/MultipleChoiceSolutionController.java
> +		boolean[] checkedSolutions = new boolean[dto.getSolutions().length];
Is this in the right order everytime?

2020-04-03 18:53 UTC, PAException reviewed
seems good

2020-04-03 18:54 UTC, merged