Everything will now be checked before deleting (#152)
E-Edu/task pull request #179
Opened 2020-04-06 00:21 UTC by PAException

## Description

Closes #152 

## Related Issue

## Type of change

- [ ] Bug fix
- [ ] Feature request
- [ ] Documenting code

## Checklists

- [ ] I referenced the according Issue
  - [ ] I created an Issue
  - [ ] I put a link in the Section [Related Issue](#related-issue)
- [ ] I tested my code with multiple browsers
- [ ] My commit messages are good and understandable

2020-04-06 08:53 UTC, steve-hb requested changes

2020-04-06 08:53 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/controller/ModuleController.java
> +	public ControllerResult<Object> deleteModule(String nameKey) {
Generic should contain specific type

2020-04-06 08:53 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/controller/SubjectController.java
> +	public ControllerResult<Object> deleteSubject(String nameKey) {
Use specific type in generic

2020-04-06 08:53 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/controller/TaskTypeController.java
> +	public ControllerResult<Object> deleteTaskType(String nameKey) {
Use specific generic type

2020-04-06 08:53 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/controller/solution/MultipleChoiceSolutionController.java
> +		if (this.multipleChoiceSolutionRepository.existsById(optionalSolution.getResult().getSolutionId()))
Will this even work?

2020-04-06 08:53 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/controller/solution/MultipleChoiceSolutionController.java
> +		ControllerResult<SolutionModel> optionalSolution = this.solutionController.getOrCreateSolution(taskId, NAME_KEY);
getOr**Create**?!

2020-04-06 08:53 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/controller/solution/MultipleChoiceSolutionController.java
> +		List<MultipleChoiceSolutionModel> multipleChoiceSolutionModels = this.multipleChoiceSolutionRepository.findAllById(
Same as in the other MR: Collection-usage is useless and we should use exist/count

2020-04-09 18:21 UTC, merged

2020-04-09 18:30 UTC, PAException commented on src/main/java/de/themorpheus/edu/taskservice/controller/solution/MultipleChoiceSolutionController.java
> +		if (this.multipleChoiceSolutionRepository.existsById(optionalSolution.getResult().getSolutionId()))
yes