Added TopicConnectionSolution (#150)
E-Edu/task pull request #215
Opened 2020-04-17 20:10 UTC by PAException

2020-04-18 20:20 UTC, steve-hb requested changes

2020-04-18 20:20 UTC, steve-hb commented on src/main/java/de/themorpheus/edu/taskservice/database/repository/solution/TopicConnectionSolutionRepository.java
> +	boolean existsBySolutionIdAndPointAAndPointB(SolutionModel solutionId, String pointA, String pointB);
pointAA?

2020-04-19 10:46 UTC, PAException commented on src/main/java/de/themorpheus/edu/taskservice/database/repository/solution/TopicConnectionSolutionRepository.java
> +	boolean existsBySolutionIdAndPointAAndPointB(SolutionModel solutionId, String pointA, String pointB);
PointA And

2020-04-19 18:59 UTC, steve-hb approved these changes

2020-04-19 19:37 UTC, merged