Issue/138 save if task is done by a user
E-Edu/task pull request #218
Opened 2020-04-18 11:09 UTC by msentwickler

## Description
Closes #138 

## Related Issue
https://github.com/E-Edu/task/issues/138

## Type of change

- [ ] Bug fix
- [x] Feature request
- [ ] Documenting code

## Checklists

- [x] I referenced the according Issue
  - [ ] I created an Issue
  - [x] I put a link in the Section [Related Issue](#related-issue)
- [ ] I tested my code with multiple browsers
- [x] My commit messages are good and understandable

2020-04-18 15:03 UTC, PAException requested changes
Please also check if taskIs banned on task/next

2020-04-18 15:03 UTC, PAException commented on src/main/java/de/themorpheus/edu/taskservice/controller/TaskController.java
> +		tasks.removeIf(tm -> userBanRepository.existsByUserId(UUID.randomUUID()) || userBanRepository.existsByUserId(UUID.randomUUID()) && !showBanned);
why two times?

2020-04-18 15:03 UTC, PAException commented on src/main/java/de/themorpheus/edu/taskservice/database/model/TaskDoneModel.java
> +	private int taskId;
Use TaskModel

2020-04-18 15:03 UTC, PAException commented on src/main/java/de/themorpheus/edu/taskservice/endpoint/TaskEndpoint.java
> +		return this.taskController.markTaskAsDone(dto.getTaskId(), dto.getDate()).getHttpResponse();
Use timestamp and generate it in the Controller

2020-04-18 15:03 UTC, PAException commented on src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/request/MarkTaskAsDoneDTO.java
> +package de.themorpheus.edu.taskservice.endpoint.dto.request;
Delete date and get taskId from a pathVariable

2020-04-18 15:03 UTC, PAException commented on src/main/java/de/themorpheus/edu/taskservice/endpoint/TaskEndpoint.java
> +		return this.taskController.markTaskAsDone(dto.getTaskId(), dto.getDate()).getHttpResponse();
rename to markTaskAsDone

2020-04-18 15:03 UTC, PAException commented on src/main/java/de/themorpheus/edu/taskservice/endpoint/TaskEndpoint.java
> +	public Object getAllTasksFromLecture(@PathVariable @NotBlank String lectureNameKey, @RequestParam boolean showBanned) {
[Make @ RequestParam not required](https://www.baeldung.com/spring-request-param#making-an-optional-request-parameter)

2020-04-18 15:03 UTC, PAException commented on src/main/java/de/themorpheus/edu/taskservice/controller/TaskController.java
> +
empty line

2020-04-18 15:09 UTC, PAException commented
And Next time create branch from experimental!!!

2020-04-19 15:21 UTC, msentwickler commented
Create a new one with right base branch.

2020-04-19 15:21 UTC, closed without merging